sandbox_server_key: SB-Mid-server-DlzYyO92Zzb3CkI5A9d1Hftk
production_server_key: Mid-server-nXNwX3E0Mw2cnpvCGfYgc5hr
sandbox_url: https://app.sandbox.midtrans.com/snap/v1/transactions
production_url: https://app.midtrans.com/snap/v1/transactions
is_production: false
app_port: 5000